name: Deploy to Pages

on:
  push:
    branches: feat/gh-pages

jobs:
  deploy-page:
    runs-on: ubuntu-latest

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    defaults:
      run:
        working-directory: gh-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install + Build
        run: docker-compose up page-build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gh-pages/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
