name: Deploy to Pages

on:
  push:
    branches: feat/gh-pages

jobs:
  deploy-page:
    runs-on: ubuntu-latest

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    defaults:
      run:
        working-directory: gh-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gh-pages/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
